/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.daos;


import com.generator.enums.PersonCardType;
import com.generator.enums.PersonPersonStatus;
import com.generator.tables.Person;
import com.generator.tables.records.PersonRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonDao extends DAOImpl<PersonRecord, com.generator.tables.pojos.Person, Integer> {

    /**
     * Create a new PersonDao without any configuration
     */
    public PersonDao() {
        super(Person.PERSON, com.generator.tables.pojos.Person.class);
    }

    /**
     * Create a new PersonDao with an attached configuration
     */
    public PersonDao(Configuration configuration) {
        super(Person.PERSON, com.generator.tables.pojos.Person.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.generator.tables.pojos.Person object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchById(Integer... values) {
        return fetch(Person.PERSON.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generator.tables.pojos.Person fetchOneById(Integer value) {
        return fetchOne(Person.PERSON.ID, value);
    }

    /**
     * Fetch records that have <code>person_name IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByPersonName(String... values) {
        return fetch(Person.PERSON.PERSON_NAME, values);
    }

    /**
     * Fetch records that have <code>card_type IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByCardType(PersonCardType... values) {
        return fetch(Person.PERSON.CARD_TYPE, values);
    }

    /**
     * Fetch records that have <code>card_num IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByCardNum(String... values) {
        return fetch(Person.PERSON.CARD_NUM, values);
    }

    /**
     * Fetch records that have <code>person_picture IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByPersonPicture(String... values) {
        return fetch(Person.PERSON.PERSON_PICTURE, values);
    }

    /**
     * Fetch records that have <code>phone_num IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByPhoneNum(String... values) {
        return fetch(Person.PERSON.PHONE_NUM, values);
    }

    /**
     * Fetch records that have <code>person_status IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByPersonStatus(PersonPersonStatus... values) {
        return fetch(Person.PERSON.PERSON_STATUS, values);
    }

    /**
     * Fetch records that have <code>create_person IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByCreatePerson(String... values) {
        return fetch(Person.PERSON.CREATE_PERSON, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByCreateTime(LocalDateTime... values) {
        return fetch(Person.PERSON.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>edit_person IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByEditPerson(String... values) {
        return fetch(Person.PERSON.EDIT_PERSON, values);
    }

    /**
     * Fetch records that have <code>edit_time IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByEditTime(LocalDateTime... values) {
        return fetch(Person.PERSON.EDIT_TIME, values);
    }

    /**
     * Fetch records that have <code>delete_person IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByDeletePerson(String... values) {
        return fetch(Person.PERSON.DELETE_PERSON, values);
    }

    /**
     * Fetch records that have <code>delete_time IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByDeleteTime(LocalDateTime... values) {
        return fetch(Person.PERSON.DELETE_TIME, values);
    }

    /**
     * Fetch records that have <code>delete_flag IN (values)</code>
     */
    public List<com.generator.tables.pojos.Person> fetchByDeleteFlag(Byte... values) {
        return fetch(Person.PERSON.DELETE_FLAG, values);
    }
}
