/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.Person;
import com.generator.tables.SchemaVersion;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Homework extends SchemaImpl {

    private static final long serialVersionUID = 1484843639;

    /**
     * The reference instance of <code>homework</code>
     */
    public static final Homework HOMEWORK = new Homework();

    /**
     * The table <code>homework.person</code>.
     */
    public final Person PERSON = com.generator.tables.Person.PERSON;

    /**
     * The table <code>homework.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = com.generator.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private Homework() {
        super("homework", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Person.PERSON,
            SchemaVersion.SCHEMA_VERSION);
    }
}
