/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.Person;
import com.generator.tables.SchemaVersion;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in homework
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>homework.person</code>.
     */
    public static final Person PERSON = com.generator.tables.Person.PERSON;

    /**
     * The table <code>homework.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = com.generator.tables.SchemaVersion.SCHEMA_VERSION;
}
