
spring:
  application:
    name: service-person
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework
  jooq:
    sql-dialect: mysql

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: service-person:8001
    prefer-ip-address: true
server:
  port: 8001